name = "dage-log-service"
main = "src/index.js"
compatibility_date = "2025-11-07"

account_id = "YourCloudflareAccountID"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "d1 database name"
database_id = "d1 database id"

[vars]
DA_WRITE_TOKEN = "Demo111+"

[observability]
enabled = true

